### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**
Fetched the version using setuptools_scm.

### CODE REVIEW

**Review by pdxjohnny — CHANGES_REQUESTED** [review]
Looks like this is failing due to `tests_require` package not getting installed. We should probably define `extras_require` (maybe under the key `dev` or `tests`) and declare zstandard as a dependency there.

We could then update the workflows to make the pip install command `.[dev]` so it gets installed


**OR** just make it a regular dependency

```
zstandard>=0.13.0 ; python_version >= "3.5"
```

**Comment by KOLANICH** [comment]
Added an extra `zstd`. But installed not the package but the dep explicitly. To install the package properly a bit more has to be done, i.e. getting rid of dffml.

**Comment by pdxjohnny** [comment]
Thanks!

P.S. It thought the version was 0.0.0 until https://github.com/srossross/rpmfile/commit/2acffc8f921de131a259802b41163b809f3eac0f

Reference: https://github.com/pypa/setuptools_scm/#setupcfg-usage

**Comment by KOLANICH** [comment]
https://github.com/srossross/rpmfile/blob/master/pyproject.toml should have installed setuptools_scm . But only relatively new versions of setuptools recognize pyproject.toml.

**Pull request merged**
